pq-code-package/mldsa-native

.github/actions/cbmc/action.yml
.github/workflows/ci.yml
mldsa/cbmc.h
mldsa/poly.c
mldsa/poly.h
proofs/cbmc/.gitignore
proofs/cbmc/Makefile.common
proofs/cbmc/Makefile_params.common
proofs/cbmc/lib/__init__.py
proofs/cbmc/lib/print_tool_versions.py
proofs/cbmc/lib/summarize.py
proofs/cbmc/list_proofs.sh
proofs/cbmc/poly_add/Makefile
proofs/cbmc/poly_add/cbmc-proof.txt
proofs/cbmc/poly_add/poly_add_harness.c
proofs/cbmc/run-cbmc-proofs.py

See the individual commit messages.
Note that CBMC is built from source and then cached in the Github cache. 
This allows us to quickly update CBMC in case there are updates, but it takes a while to build the first time (~15 minutes on the ubuntu-latest runners). 
In case this is not needed at some point, we may want to switch to the pre-built packages available in nix.
For now the CI runs on the default github Ubuntu runners. They are not super powerful, so once we have a large number of proofs we may want to switch to beefier machines (as in mlkem-native). 
* Resolves https://github.com/pq-code-package/mldsa-native/issues/8

Add CBMC infrastructure and prove `poly_add`

---

mldsa/sign.c
mldsa/sign.h

This PR implements the internal/external split of ML-DSA keygen as described in [FIPS 204](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.204.pdf).
This will allow us to perform ACVP testing for internal functions, and brings us closer to the FIPS 204 specification.

implement FIPS 204 Alg 6 keygen_internal

---

mldsa/poly.c
mldsa/poly.h
proofs/cbmc/poly_shiftl/Makefile
proofs/cbmc/poly_shiftl/poly_shiftl_harness.c

Resolves #23. Depends on #53.
This commit adds the CBMC proof for poly_shiftl.
The reference implementation is using an explicit left shift - this has
undefined behaviour for negative values in C90/C99.
This commit instead uses an explicit multiplication.
Both gcc14 and clang20 turn this into a logical shift even with -O0.

CBMC: Contract and proof for poly_shiftl

---

mldsa/sign.c
mldsa/sign.h
test/acvp_mldsa.c

This PR implements the external-mu variant of ML-DSA signing and verification as specified in FIPS 204. The changes allow direct input of the mu value rather than computing it from the message during signing and verification.
- Added `crypto_sign_signature_extmu()` and `crypto_sign_verify_extmu()` functions that accept pre-computed mu values
- Modified internal signing/verification functions to support an external mu mode flag
- Updated function documentation to reference relevant FIPS 204 algorithms
- Maintained backward compatibility with existing signing/verification APIs
- Uses a boolean flag `externalmu` to control mu handling in internal functions
- Skips CRH computation when mu is provided externally
- Copies external mu directly when in external mode
The external-mu mode enables …

Implementation of external-mu mode for ML-DSA signing and verification

---

proofs/cbmc/Makefile.common

Currently CBMC defaults to use gcc. This is a problem when on MacOS, where
we default to clang. On these systems our CBMC proofs only work if the user
happens to have gcc in their $PATH.
This commit changes the flags for goto-cc to use the compiler set in $CC which
is clang on MacOS and gcc on other platforms.

CBMC: switch --native-compiler to $(CC) instead of gcc

---

flake.nix
nix/cbmc/default.nix
nix/hol_light/default.nix
nix/s2n_bignum/default.nix

This pulls in the most recent nix configuration from mlkem-native. Most notably this includes the recently released CBMC 6.5.0.
It also updates HOL-Light which is not required yet for mldsa-native, but let's keep it in sync.

Update CBMC to 6.5.0

---

mldsa/poly.c
mldsa/poly.h
mldsa/polyvec.c
mldsa/polyvec.h
mldsa/rounding.h
proofs/cbmc/make_hint/Makefile
proofs/cbmc/make_hint/make_hint_harness.c
proofs/cbmc/poly_make_hint/Makefile
proofs/cbmc/poly_make_hint/poly_make_hint_harness.c
proofs/cbmc/polyveck_make_hint/Makefile
proofs/cbmc/polyveck_make_hint/polyveck_make_hint_harness.c

Add contracts and proofs of type-safety for
```
rounding.c - make_hint()
poly.c     - poly_make_hint()
polyvec.c  - polyveck_make_hint()
```
The final one of those gives an upper-bound on the number of "1" bits in a hint, which
can be used in the proof of pack_sig()
Resolves #21

Add proofs of XXX_make_hint() in support of proof of pack_sig()

---

mldsa/packing.c
mldsa/packing.h
mldsa/polyvec.c
mldsa/polyvec.h
mldsa/sign.c
proofs/cbmc/pack_sig/Makefile
proofs/cbmc/pack_sig/pack_sig_harness.c
proofs/cbmc/polyvecl_pack_z/Makefile
proofs/cbmc/polyvecl_pack_z/polyvecl_pack_z_harness.c

Fixes #72 
1. Simplifies pack_sig() through use of memcpy() and memset() where possible.
2. Introduces new function polyvecl_pack_z() in polyvec.[hc] and its proof.
3. Adds formal parameter "number_of_hints" to pack_sig() and pre-condition that can be used to ensure type-safety.
4. Updates call to pack_sig() in sign.c appropriately.
5. Proof of pack_sig() updated.
Please review explanatory comments in body of pack_sig()

proof of pack_sig

---

scripts/tests

This PR fixes the tests script for ACVP tests with 'all' argument.
Solves https://github.com/pq-code-package/mldsa-native/issues/81.
```
./scripts/tests all
INFO  > Functional Test    Compile     (native no_opt):  make func OPT=0 AUTO=1 -j16
INFO  > Kat Test           Compile     (native no_opt):  make kat OPT=0 AUTO=1 -j16
INFO  > Nistkat Test       Compile     (native no_opt):  make nistkat OPT=0 AUTO=1 -j16
INFO  > ACVP Test          Compile     (native no_opt):  make acvp OPT=0 AUTO=1 -j16
INFO  > Functional Test    ML-DSA-44   (native no_opt):  make run_func_44 -j16
INFO  > Functional Test    ML-DSA-65   (native no_opt):  make run_func_65 -j16
INFO  > Functional Test    ML-DSA-87   (native no_opt):  make run_func_87 -j16
INFO  > Kat Test           ML-DSA-44   (native no_opt):  make …
```

Fix bug in tests script

---

mldsa/poly.c
mldsa/poly.h
proofs/cbmc/poly_sub/Makefile
proofs/cbmc/poly_sub/poly_sub_harness.c

This PR adds the spec and proof for `poly_sub` function. 
This PR does _not_ remove `poly_sub` benchmarking `DBENCH_START();` and `DBENCH_STOP(*tsub);` calls.
Solves https://github.com/pq-code-package/mldsa-native/issues/22.

Add spec and proof for poly_sub

---

mldsa/poly.c
proofs/cbmc/rej_eta/Makefile
proofs/cbmc/rej_eta/rej_eta_harness.c

This PR adds the spec and proof for rej_eta function.
Notes::
- `rej_eta` is static, thus, `CHECK_FUNCTION_CONTRACTS` is defined as `rej_eta` instead of $`(MLD_NAMESPACE)rej_eta` in the `Makefile`.
- `rej_eta` is static, thus, additional assumptions, such as `requires(len <= MLDSA_N && buflen <= (POLY_UNIFORM_ETA_NBLOCKS * STREAM256_BLOCKBYTES))` are made. This accelerates the performance of CBMC proofs.
Another Note::
- [change types](https://github.com/manastasova/mldsa-native/blob/783550404c42fa5659f4116d8b7c177c32a4d2b6/mldsa/poly.c#L442) `uint32_t t0, t1;` to `int32_t t0, t1;` due to [potential overflow in](https://github.com/manastasova/mldsa-native/blob/783550404c42fa5659f4116d8b7c177c32a4d2b6/mldsa/poly.c#L467) `if (t0 < 9){a[ctr++] = 4 - t0;}` causing cbmc fail.
Solves …

Add spec and proof for rej_eta

---

mldsa/ntt.c
mldsa/params.h
mldsa/reduce.c
mldsa/reduce.h
proofs/cbmc/fqmul/Makefile
proofs/cbmc/fqmul/fqmul_harness.c
proofs/cbmc/montgomery_reduce/Makefile
proofs/cbmc/montgomery_reduce/montgomery_reduce_harness.c

Resolves https://github.com/pq-code-package/mldsa-native/issues/14
This follows closely montgomery_reduce in mlkem-native: https://github.com/pq-code-package/mlkem-native/blob/83d85fe224bd6cf1b75f096a2b2fa01033b3dfda/mlkem/poly.h#L80
@hanno-becker @rod-chapman - can we prove anything else about this montgomery_reduction? The contract right now is rather weak. Do you remember why it is this weak in mlkem-native?

CBMC: Add contract and proof for `montgomery_reduce` and `fqmul`

---

mldsa/cbmc.h
mldsa/poly.c
mldsa/poly.h
mldsa/rounding.c
mldsa/rounding.h
proofs/cbmc/poly_use_hint/Makefile
proofs/cbmc/poly_use_hint/poly_use_hint_harness.c
proofs/cbmc/use_hint/Makefile
proofs/cbmc/use_hint/use_hint_harness.c

Fixes #20 
Adds contracts and CBMC proofs of use_hint() and poly_use_hint()
polyveck_use_hint() will be attempted separately.
All tests, proofs, and lint OK.

Proofs of `use_hint()` and `poly_use_hint()`

---

mldsa/rounding.c
mldsa/rounding.h

Moves comments from rounding.c to their correct place in rounding.h
Clarifies wording in 2 places.
Lint OK. Tests OK.

Move and clarify comments in rounding.c to rounding.h

---

mldsa/poly.c
proofs/cbmc/rej_uniform/Makefile
proofs/cbmc/rej_uniform/rej_uniform_harness.c

This PR adds the contract and proof for rej_uniform function.
Notes::
- `rej_uniform` is static, thus, `CHECK_FUNCTION_CONTRACTS` is defined as `rej_uniform` instead of $`(MLD_NAMESPACE)rej_uniform` in the `Makefile`.
- `rej_uniform` is static, thus, additional assumptions, such as `requires(len <= MLDSA_N && buflen <= (POLY_UNIFORM_NBLOCKS * STREAM128_BLOCKBYTES))` are made. This accelerates the performance of CBMC proofs.
Solves https://github.com/pq-code-package/mldsa-native/issues/25.

Add spec and proof for rej_uniform

---

mldsa/poly.c
mldsa/poly.h
mldsa/reduce.c
mldsa/reduce.h
proofs/cbmc/poly_reduce/Makefile
proofs/cbmc/poly_reduce/poly_reduce_harness.c

1. Adds spec for `poly_reduce` using proof for reduce32. Fixes #64.
2. Edits `reduce32` proof to use `cassert` instead of `ensures`.
3. Edits `cbmc.h` to ignore `cassert` statements unless doing a CBMC proof.
4. Moves `REDUCE_*` defines from `reduce.h`, `poly.h` to common header file `params.h` to avoid divergent values. The defines are renamed as per convention.

Add proof for poly_reduce

---

mldsa/ntt.h
mldsa/packing.c
mldsa/packing.h
mldsa/poly.c
mldsa/poly.h
mldsa/polyvec.c
mldsa/polyvec.h
mldsa/sign.c
mldsa/sign.h

Following https://github.com/pq-code-package/mldsa-native/pull/97, this commit moves _all_ comments documenting function signatures into the corresponding header files.
Note that there are still some functions that do not have a documenting comment.
I have not changed any comments except for alignment.

Move all docstrings to header files

---

.github/actions/bench/action.yml
.github/workflows/bench.yml

Depends on #49.
Once merged to main, this should create a website in the [gh-pages branch ](https://github.com/pq-code-package/mldsa-native/tree/gh-pages) similar to https://pq-code-package.github.io/mlkem-native/dev/bench/ that we can use to keep track of performance changes over time. 
Once we have a baseline the bechmarks will trigger comments in pull requests showing the performance change.
If that all works I can easily add Raspberry Pi5, Cortex-A55, and Banana Pi F3 (rv64) benchmarks. We can also add the AWS EC2-based benchmarks then, but that's a bit more work.

Adds benchmarking on Raspberry Pi 4 (Cortex-A72)

---

mldsa/cbmc.h
mldsa/poly.c
mldsa/poly.h
mldsa/reduce.h
proofs/cbmc/poly_caddq/Makefile
proofs/cbmc/poly_caddq/poly_caddq_harness.c
proofs/cbmc/poly_chknorm/Makefile
proofs/cbmc/poly_chknorm/poly_chknorm_harness.c
proofs/cbmc/poly_ntt/Makefile
proofs/cbmc/poly_ntt/poly_ntt_harness.c
proofs/cbmc/poly_pointwise_montgomery/Makefile
proofs/cbmc/poly_pointwise_montgomery/poly_pointwise_montgomery_harness.c
proofs/cbmc/poly_power2round/Makefile
proofs/cbmc/poly_power2round/poly_power2round_harness.c

This adds specs + proofs for all remaining `poly_` that don't have a dependency on Keccak. 
Resolves https://github.com/pq-code-package/mldsa-native/issues/108
Resolves https://github.com/pq-code-package/mldsa-native/issues/104
Resolves https://github.com/pq-code-package/mldsa-native/issues/105
Resolves https://github.com/pq-code-package/mldsa-native/issues/107
Resolves https://github.com/pq-code-package/mldsa-native/issues/109
The last one is by far the most intersting one. I'd actually like some help from the CBMC experts: What I have now seems to work fine: 
```c
int poly_chknorm(const poly *a, int32_t B)
__contract__(
requires(memory_no_alias(a, sizeof(poly)))
requires(B <= (MLDSA_Q - 1) / 8)
requires(array_bound(a->coeffs, 0, MLDSA_N, -REDUCE_RANGE_MAX, REDUCE_RANGE_MAX)) …
```

CBMC: Add contracts and proofs for various poly functions

---

mldsa/fips202/fips202.c
mldsa/fips202/fips202.h
proofs/cbmc/load64/Makefile
proofs/cbmc/load64/load64_harness.c
proofs/cbmc/store64/Makefile
proofs/cbmc/store64/store64_harness.c

This PR adds the spec and proofs for load64 and store64.
Notes::
- Change the signature of function `store64` from `static void store64(uint8_t x[8], uint64_t u)` to `static void store64(uint8_t x[8], const uint64_t u)`, marking the input as a `const`.
-  Add explicit `& 0xFF` before casting `uint64_t u` to `uint8_t x[i]` to prevent overlflows

Add spec and proofs for load64 and store64

---

mldsa/poly.c
mldsa/poly.h
mldsa/polyvec.c
mldsa/polyvec.h
proofs/cbmc/polyveck_add/Makefile
proofs/cbmc/polyveck_add/polyveck_add_harness.c
proofs/cbmc/polyveck_pack_w1/Makefile
proofs/cbmc/polyveck_pack_w1/polyveck_pack_w1_harness.c
proofs/cbmc/polyveck_reduce/Makefile
proofs/cbmc/polyveck_reduce/polyveck_reduce_harness.c
proofs/cbmc/polyveck_sub/Makefile
proofs/cbmc/polyveck_sub/polyveck_sub_harness.c
proofs/cbmc/polyveck_use_hint/Makefile
proofs/cbmc/polyveck_use_hint/polyveck_use_hint_harness.c
proofs/cbmc/polyvecl_add/Makefile
proofs/cbmc/polyvecl_add/polyvecl_add_harness.c
proofs/cbmc/polyvecl_reduce/Makefile
proofs/cbmc/polyvecl_reduce/polyvecl_reduce_harness.c

- Depends on https://github.com/pq-code-package/mldsa-native/pull/140
- Resolves https://github.com/pq-code-package/mldsa-native/issues/116
- Resolves https://github.com/pq-code-package/mldsa-native/issues/117
- Resolves https://github.com/pq-code-package/mldsa-native/issues/124
- Resolves https://github.com/pq-code-package/mldsa-native/issues/126
- Resolves https://github.com/pq-code-package/mldsa-native/issues/127
- Resolves https://github.com/pq-code-package/mldsa-native/issues/136
- Resolves https://github.com/pq-code-package/mldsa-native/issues/135
`polyvecl_add`, `polyveck_add`, `polyveck_sub`,`polyveck_use_hint`, `polyveck_reduce`, `polyvecl_reduce` were too slow when using unrolling - I instead did a direct proof with the workaround from #92. I added them to #102 to remove the …

CBMC: Add contracts and proofs for various polyvec functions

---

mldsa/packing.c
mldsa/packing.h
mldsa/poly.h
mldsa/polyvec.c
mldsa/polyvec.h
proofs/cbmc/polyveck_pack_eta/Makefile
proofs/cbmc/polyveck_pack_t0/Makefile
proofs/cbmc/polyveck_unpack_eta/Makefile
proofs/cbmc/polyveck_unpack_t0/Makefile
proofs/cbmc/polyvecl_unpack_z/Makefile
proofs/cbmc/polyvecl_unpack_z/polyvecl_unpack_z_harness.c
proofs/cbmc/unpack_hints/Makefile
proofs/cbmc/unpack_hints/unpack_hints_harness.c
proofs/cbmc/unpack_sig/Makefile
proofs/cbmc/unpack_sig/unpack_sig_harness.c

Re-factors unpack_sig() to make it much simplifer, and isolates unpacking of hints into new, static unpack_hints() function
Adds supporting functions and their proofs:
poly_clear() - zeroes a polynomial
polyveck_clear() - zeroes a vector of K polynomials
polyvecl_unpack_z() - unpacks the L z components of a signature
unpack_hints() - the inverse of the "hint packing" algorithm in pack_sig()
All proofs OK. All tests OK. Lint OK.

Simplification and proof of unpack_sig() and supporting functions.

---

mldsa/polyvec.c
mldsa/polyvec.h
proofs/cbmc/polyveck_caddq/Makefile
proofs/cbmc/polyveck_caddq/polyveck_caddq_harness.c
proofs/cbmc/polyveck_ntt/Makefile
proofs/cbmc/polyveck_ntt/polyveck_ntt_harness.c
proofs/cbmc/polyveck_power2round/Makefile
proofs/cbmc/polyveck_power2round/polyveck_power2round_harness.c
proofs/cbmc/polyvecl_ntt/Makefile
proofs/cbmc/polyvecl_ntt/polyvecl_ntt_harness.c

- Depends on #151
- Resolves https://github.com/pq-code-package/mldsa-native/issues/118
- Resolves https://github.com/pq-code-package/mldsa-native/issues/129
- Resolves https://github.com/pq-code-package/mldsa-native/issues/125
- Resolves https://github.com/pq-code-package/mldsa-native/issues/133
I moved the slow proofs from #151 out, so we can work on them separately. 
Update: I used the workaround from #92 to make the four proofs fast using a temporary polynomial. That's a temporary workaround for https://github.com/diffblue/cbmc/issues/8617. I added the functions to #102, so that we can remove the workaround later.

CBMC: Add contracts and proofs for more polyvec functions

---

mldsa/fips202/fips202.c
mldsa/fips202/fips202.h
proofs/cbmc/Makefile_params.common
proofs/cbmc/keccakf1600_absorb_once/Makefile
proofs/cbmc/keccakf1600_absorb_once/keccakf1600_absorb_once_harness.c
proofs/cbmc/keccakf1600_permute/Makefile
proofs/cbmc/keccakf1600_permute/keccakf1600_permute_harness.c
proofs/cbmc/sha3_256/Makefile
proofs/cbmc/sha3_256/sha3_256_harness.c
proofs/cbmc/sha3_512/Makefile
proofs/cbmc/sha3_512/sha3_512_harness.c
proofs/cbmc/shake128_absorb_once/Makefile
proofs/cbmc/shake128_absorb_once/shake128_absorb_once_harness.c
proofs/cbmc/shake256_absorb_once/Makefile
proofs/cbmc/shake256_absorb_once/shake256_absorb_once_harness.c

This PR adds the spec and proofs for different Keccak dependent functions including:  
- `KeccakF1600_StatePermute`
- `keccak_absorb_once`
- `shake128_absorb_once`
- `shake256_absorb_once`
- `sha3_256`
- `sha3_512`

Add spec and proofs for Keccak dependent functions

---

mldsa/polyvec.c
mldsa/polyvec.h
proofs/cbmc/polyvecl_invntt_tomont/Makefile
proofs/cbmc/polyvecl_invntt_tomont/polyvecl_invntt_tomont_harness.c

- Resolves https://github.com/pq-code-package/mldsa-native/issues/119
Depends on: https://github.com/pq-code-package/mldsa-native/pull/180 to be merged first, I can then rebase.

CBMC: Add contract and proof for polyvecl_invntt_tomont

---

proofs/cbmc/lib/summarize.py

CBMC-Starter_Kit PR#207 (https://github.com/model-checking/cbmc-starter-kit/pull/207)
fixed a defect where the total number of proofs reported is one too big when
cbmc-run-proofs.py --summarize is run.
This PR imports that fix into the mldsa-native repo.

Fix reporting of total proof count in cbmc-starter-kit

---

mldsa/fips202/fips202.c
mldsa/fips202/fips202.h
proofs/cbmc/shake128_squeezeblocks/Makefile
proofs/cbmc/shake128_squeezeblocks/shake128_squeezeblocks_harness.c

Resolves https://github.com/pq-code-package/mldsa-native/issues/142
Was reviewing Mila's current PR and was testing functionality of the `keccak_squeezeblocks` contract by thinking through possible values of `r`. I wrote this test code to test it for the case of `shake128_squeezeblocks` and thought I may as well complete the proof (as the remaining poly/polyvec functions now rely on the fips202 ones for sampling).
Depends on https://github.com/pq-code-package/mldsa-native/pull/187

CBMC: Add proof and contract for shake128_squeezeblocks

---

mldsa/symmetric-shake.c
mldsa/symmetric.h
proofs/cbmc/mldsa_shake128_stream_init/Makefile
proofs/cbmc/mldsa_shake128_stream_init/mldsa_shake128_stream_init_harness.c

Resolves https://github.com/pq-code-package/mldsa-native/issues/141

CBMC: Add proof and contract for mldsa_shake128_stream_init

---

.clang-format
mldsa/fips202/fips202.h
mldsa/poly.c
mldsa/poly.h
proofs/cbmc/poly_challenge/Makefile
proofs/cbmc/poly_challenge/poly_challenge_harness.c

Fixes #113 
Adds contracts and proof support files for poly_challenge()

Proof of poly_challenge() including contracts

---

.github/workflows/bench.yml
.github/workflows/bench_ec2_any.yml
.github/workflows/bench_ec2_reusable.yml
.github/workflows/ci.yml
.github/workflows/ci_ec2_reusable.yml

This commit adds benchmarking on
- Graviton 2 (t4g.small)
- Graviton 3 (c7g.medium)
- Graviton 4 (c8g.medium)
- AMD EPYC 4th gen (c7a.medium)
- Intel Xeon 4th gen (c7i.metal-24xl)
- AMD EPYC 3rd gen (c6a.large)
- Intel Xeon 3rd gen (c6i.large)
With that we have all the platforms that are covered in mlkem-native.

Add EC2 benchmarking

---

mldsa/poly.c
proofs/cbmc/rej_uniform/rej_uniform_harness.c

Working on addressing Hanno's [comment](https://github.com/pq-code-package/mldsa-native/pull/202#pullrequestreview-2818915323) to refactor `rej_uniform` as was done in [mlkem-native](https://github.com/pq-code-package/mlkem-native/blob/main/mlkem/sampling.c) to facilitate the proof for `poly_uniform`.
Alligning the implementation of `poly_uniform` to be up to date with changes to the reference implementation of kyber (https://github.com/pq-crystals/kyber/commit/ce492cd3d56bfca61bd941b6a73da3764e799aae).

CBMC: Refactor rej_uniform and poly_uniform functions

---

mldsa/fips202/fips202.c
proofs/cbmc/keccakf1600_extract_bytes/Makefile
proofs/cbmc/keccakf1600_extract_bytes/keccakf1600_extract_bytes_harness.c

This PR introduces the function `keccakf1600_extract_bytes` which optimizes the CBMC proof latency for `keccak_squeezeblocks` to 48s (previously ~150s).
Notes:
- Introduce `keccakf1600_extract_bytes` function as it is defined in mlkem-native - https://github.com/pq-code-package/mlkem-native/blob/ae2afe58380797f6b6789060b3ff8be2b2917fb5/mlkem/fips202/keccakf1600.c#L38 
- The main speedup was observed after adding support for both little- and big-endian.

Optimize proof for `keccak_squeezeblocks`

---

mldsa/fips202/fips202.c
mldsa/fips202/fips202.h
mldsa/poly.c
mldsa/symmetric.h
proofs/cbmc/keccak_squeeze/Makefile
proofs/cbmc/keccak_squeeze/keccak_squeeze_harness.c
proofs/cbmc/shake128/Makefile
proofs/cbmc/shake128/shake128_harness.c
proofs/cbmc/shake128_squeeze/Makefile
proofs/cbmc/shake128_squeeze/shake128_squeeze_harness.c
proofs/cbmc/shake256/Makefile
proofs/cbmc/shake256/shake256_harness.c
proofs/cbmc/shake256_squeeze/Makefile
proofs/cbmc/shake256_squeeze/shake256_squeeze_harness.c

This PR is a continuation of https://github.com/pq-code-package/mldsa-native/pull/187 and adds specs and proofs for the following functions: 
- keccak_squeeze
- shake128_squeeze
- shake256_squeeze
- shake128
- shake256

Add spec and proofs for all fips202 functions

---

mldsa/poly.c
proofs/cbmc/rej_eta/Makefile
proofs/cbmc/rej_eta/rej_eta_harness.c

Preparation for the CBMC proof of `poly_uniform_eta`. Similarly to https://github.com/pq-code-package/mldsa-native/pull/218 we need to refactor `rej_eta` to remove pointer arithmetic within the argument. The function `poly_uniform_eta` has been modified to accept the changes to `rej_eta`.

CBMC: Refactored rej_eta and poly_uniform_eta

---

proofs/cbmc/keccakf1600_extract_bytes_BE/Makefile
proofs/cbmc/keccakf1600_extract_bytes_BE/keccakf1600_extract_bytes_be_harness.c

Fixes #226 
Adds proof for the big-endian version of keccakf1600_extract_bytes() function.
Changes to the proof Makefile are based on similar version in mlkem-native.

Add proof for big-endian version of keccakf1600_extract_bytes()

---

RELICENSE.md

This PR adds a RELICENSE file. The purpose of this file is to gather consent from mldsa-native contributors that their contributions may be relicensed as Apache-2.0 OR MIT OR ISC.
The relicensing itself is planned to be carried out once all contributors have added their names to that file.
Contributors agreeing to the relicensing should push a separate commit adding their name to RELICENSE.

Contributor's agreement to relicensing mldsa-native under Apache-2.0 OR ISC OR MIT

---

proofs/cbmc/invntt_layer/Makefile
proofs/cbmc/poly_invntt_tomont/Makefile
proofs/cbmc/polyvecl_unpack_z/Makefile

I have found 3 functions whose proof is slow with Bitwuzla, but much faster with Z3.
Results on Mac M1:
polyvecl_unpack_z() - from 90s to 5s
poly_invntt_tomont() - from 75s to 5s
mld_invntt_layer() - from 65s to 30s
These were some of the most expensive proofs in the library, so reduce wall-clock time for the full proof run, even on large multi-core machines.

Switch these proofs to use Z3 rather than Bitwuzla

---

.github/actions/setup-nix/action.yml

The nix-post-check step in the setup-nix action used a conditional that is incorrectly using ${{ steps.nix-pre-check.outputs.installed }} as a raw value instead of a string causing a error in case the value is undefined. This commit wraps it quotes fixing the issue.
Related to https://github.com/pq-code-package/mlkem-native/issues/1033

Fix: conditional in nix-post-check step in setup-nix action

---

mldsa/polyvec.c
mldsa/polyvec.h

This commit refactors polyvecl_pointwise_acc_montgomery in preparation of pulling in native code for this function.
For the optimized backends, this function will perform the accumulation of the products on 64-bit words prior to reducing it back to 32-bit, e.g., using Montgomery reduction.
This requires a pre-condition that this accumulation cannot overflow an int64_t. This is the case as in all call sites the second input is the output of an NTT which is bounded by 9q.
As a side-effect this commit allows proving the bounds using CBMC. Before the function was simply calling poly_pointwise_montgomery which does not provide any bounds on the inputs/outputs. Consequently the proof of the accumulation of those outputs to not overflow would be impossible.

Refactor polyvecl_pointwise_acc_montgomery in preparation of native code

---

mldsa/polyvec.c
mldsa/polyvec.h
proofs/cbmc/polyveck_chknorm/Makefile
proofs/cbmc/polyveck_chknorm/polyveck_chknorm_harness.c

Fixes #132 
Adds contracts and proof files for polyveck_chknorm()
Proofs, lint and tests OK.

Add contracts and proof files for polyveck_chknorm()

---

.github/workflows/all.yml
.github/workflows/base.yml
.github/workflows/cbmc.yml
.github/workflows/ci.yml
flake.lock
flake.nix
nix/cbmc/0001-Do-not-download-sources-in-cmake.patch
nix/cbmc/0002-Do-not-download-sources-in-cmake.patch
nix/cbmc/default.nix
nix/slothy/default.nix
nix/util.nix

- Resolves https://github.com/pq-code-package/mldsa-native/issues/285
Similar to https://github.com/pq-code-package/mlkem-native/pull/1041
Additionally, refactoring the CI to align with mlkem-native
[NixOS 25.05 ](https://nixos.org/blog/announcements/2025/nixos-2505/) has been released yesterday bringing various version updates also to nixpkgs.
Notable changes for us are: 
- Default clang/llvm is now 19; we switch to the default in the core shells
- Default gcc is now 14; we switch to it in the core shells
- gcc 7, zig_0_10, zig_0_11 are not longer supported in 25.05; we instead
take it from nixpkgs 24.05
- zig_0_14 has been added; we test in CI now as well
- Unicorn and protobuf versions are now compatible with SLOTHY simpliying the
build
- z3 has been updated to 4.15.0; we take it from …

Update to nixpkgs 25.05

---

.github/workflows/ci.yml
flake.nix

- Ports https://github.com/pq-code-package/mlkem-native/pull/1083 from mlkem-native. 
zig0.11 seems to have dropped from the nix binary cache for MacOS. This means it has to be built from source in the CI significanlty slowing down CI.
Note that both zig 0.10 and zig 0.11 have been dropped in nixpkgs 25.05, so it is expected that it is eventually dropped from the cache. This commit removes zig 0.11 and the even older zig 0.10.

Nix: Remove zig 0.10 and zig 0.11 shells and CI

---

mldsa/ntt.c
mldsa/ntt.h
mldsa/poly.c
mldsa/poly.h
mldsa/polyvec.c
mldsa/polyvec.h
proofs/cbmc/fqscale/Makefile
proofs/cbmc/fqscale/fqscale_harness.c

- Resolves #312 
Add the stronger post-condition to following function and rewrite the CBMC proof if necessary:

CBMC: Prove stronger post-condition for `invntt_tomont`

---

scripts/tests

https://github.com/pq-code-package/mldsa-native/pull/307 changes the output format of the benchmarks adding an 'avg'.
This broke the parsing of the benchmarks that is required for the Github benchmark action.
This commit fixes that parsing and restores the benchmarking in CI.

Fix benchmark parsing

---

mldsa/polyvec.c
mldsa/polyvec.h
proofs/cbmc/polyveck_add/Makefile
proofs/cbmc/polyvecl_add/Makefile

- Resolves #311 
In https://github.com/pq-code-package/mldsa-native/issues/311, it was
identified that the current post-conditions are insufficent to complete
the higher level proofs.
There are 3 different places where polynomial additions are required
and they come with different input/output bounds:
Case 1: polyvecl_add in Signing
Inputs (-q, q) -- actual bound is tigher, but this suffices
Outputs (-2q, 2q)
Case 2: polyveck_add in Signing
Inputs (-q, q)
Outputs (-2q, 2q) -- no output bound required
Case 3: polyveck_add in Key Generation
Inputs (-4211139, 4211139) and (-4, 4) -- can relax to something like (-3q/4, 3q/4) and (-q/4, q/4)
Outputs (-q, q) -- this is a strict bound for the following to work.
It appears best to prove correctness of the addition itself, then the bound
reasoning …

Strengthen post-condition of `polyveck_add` and `polyvecl_add`

---

mldsa/sign.c
mldsa/sign.h
proofs/cbmc/crypto_sign_verify/Makefile
proofs/cbmc/crypto_sign_verify/crypto_sign_verify_harness.c
proofs/cbmc/crypto_sign_verify_extmu/Makefile
proofs/cbmc/crypto_sign_verify_extmu/crypto_sign_verify_extmu_harness.c

- Resolves #277 
- Resolves #278
Please review that first.
This PR add the spec and proof for `crypto_sign_verify`, `crypto_sign_verify_extmu`
for `crypto_sign_verify_extmu`, the following has been changed:
- Add cbmc proof for crypto_sign_verify_extmu
- Strengthen crypto_sign_verify_internal's contract
- Add the mu's length in crypto_sign_verify_extmu

CBMC: Add the spec and proof for crypto_sign_verify, crypto_sign_verify_extmu

---

mldsa/config.h

- Resolves #11 
CRYPTO_ALGNAME is an artifact of the old NISTKAT testvectors that were removed in https://github.com/pq-code-package/mldsa-native/pull/323. It can be safely removed.
This is the last macro that was not properly namespaced, this hence resolves https://github.com/pq-code-package/mldsa-native/issues/11.

Remove CRYPTO_ALGNAME (NISTKAT test artifact)

---

mldsa/packing.c
mldsa/poly.c
mldsa/poly.h
mldsa/polyvec.c
mldsa/polyvec.h
nix/cbmc/default.nix
nix/cbmc/z3-lower-bound-typo.patch
proofs/cbmc/pack_pk/Makefile
proofs/cbmc/polyveck_decompose/Makefile
proofs/cbmc/polyveck_pack_eta/Makefile
proofs/cbmc/polyveck_pack_t0/Makefile
proofs/cbmc/polyveck_pack_w1/Makefile
proofs/cbmc/polyvecl_pack_eta/Makefile
proofs/cbmc/polyvecl_pack_z/Makefile
proofs/cbmc/polyvecl_pointwise_acc_montgomery/Makefile

We have noticed a severe performance degradation of some CBMC proofs when moving from z3 4.12 to 4.13/4.14/4.15. This is currently blocking the proof of the signing functions.
This PR downgrades back to z3 4.12.6 - the last release prior to the performance regression. A few minor changes to the other CBMC proofs are required which are applied as part of this PR.

Downgrade to z3 4.12.6 and adjust CBMC proofs

---

mldsa/packing.h
mldsa/poly.c
mldsa/poly.h
mldsa/polyvec.c
mldsa/polyvec.h
mldsa/sign.c
mldsa/sign.h
proofs/cbmc/crypto_sign_signature_internal/Makefile
proofs/cbmc/crypto_sign_signature_internal/crypto_sign_signature_internal_harness.c
proofs/cbmc/mld_attempt_signature_generation/Makefile
proofs/cbmc/mld_attempt_signature_generation/mld_attempt_signature_generation_harness.c
proofs/cbmc/polyveck_chknorm/Makefile
proofs/cbmc/polyvecl_chknorm/Makefile
proofs/cbmc/polyvecl_pointwise_acc_montgomery/Makefile

Fixes #272 
Refactor and add proof files for crypto_sign_signature_internal()
Introduce new local function mld_attempt_signature_generation() to simplify and stabilize proofs.
Strengthen contracts for
mld_poly_make_hint()
mld_polyveck_make_hint()
mld_pack_sig()
in support of that goal.
Adjust CBMC flags for proof stability on macOS and Linux

Refactor and add proof files for crypto_sign_signature_internal()

---

mldsa/sign.c
mldsa/sign.h
proofs/cbmc/Makefile_params.common
proofs/cbmc/crypto_sign/Makefile
proofs/cbmc/crypto_sign/crypto_sign_harness.c
proofs/cbmc/crypto_sign_signature/Makefile
proofs/cbmc/crypto_sign_signature/crypto_sign_signature_harness.c
proofs/cbmc/crypto_sign_signature_extmu/Makefile
proofs/cbmc/crypto_sign_signature_extmu/crypto_sign_signature_extmu_harness.c

Fixes #273
Fixes #274
Fixes #275 
Add contracts and proofs for top-level signature functions:
crypto_sign_signature()
crypto_sign_signature_extmu()
crypto_sign()
Also adjust the Makefile_params.common file for CBMC to define the MLD_NAMESPACETOP macro for crypto_sign()

Add contracts and proofs for top-level signature functions

---

mldsa/sign.h

- Resolves  #356 
cbmc: add the `m == sm` exception to crypto_sign_open's cbmc contract.

CBMC: Allow `m == sm` aliasing for crypto_sign_open

---

mldsa/polyvec.h

- Resolves #366 
This PR add the missing docstrings for following:
- polyveck_pack_eta
- polyvecl_pack_eta
- polyvecl_pack_z
- polyveck_pack_t0
- polyvecl_unpack_eta
- polyvecl_unpack_z
- polyveck_unpack_eta
- polyveck_unpack_t0

Add missing docstrings in polyvec.h

---

META.yml
test/gen_KAT.c

Currently our KAT tests do not work in case the pairwise-consistency test (PCT) is enabled through MLD_CONFIG_KEYGEN_PCT. The reason for this is that when PCT is enabled, a signature is generated at the end of key generation which requires randomness to be sampled from randombytes() messing with the state of the deterministic random number generator used for KAT tests.
To work around this, this commit changes the KAT tests to follow the same approach that is also used by mlkem-native: Only use the de-randomized APIs and derive all random coins deterministically using SHAKE instead of randombytes().
This enabled KAT tests even when PCT is enabled.
Unfortunately, it requires changing the KAT hashes once.
CI to test this will be added in …

Adjust KAT test to work with PCT

---

mldsa/fips202/fips202.c

To avoid a potential overflow in ```pos + inlen```, I'm proposing to rewrite:
```
while (pos + inlen >= r)
```
as
```
while (inlen >= r - pos)
```
Note that there cannot be an underflow in the subtraction, as ```pos <= r``` is a precondition.

FIPS 202: avoid potential overflow in addition

---

.github/workflows/bench.yml
.github/workflows/ci.yml
flake.nix
nix/util.nix

- Resolves: #439 
- Previously, we used a single `ci-cross` nix shell for all cross-compilation tool chains. This shell takes a very long time to build and is therefore inconvenient to use for cross-compilation on a specific target.
- This commit extends the nix flake by architecture specific ci cross shells:
- ci-cross-x86_64
- ci-cross-aarch64
- ci-cross-riscv64
- ci-cross-riscv32
- ci-cross-ppc64le
- ci-cross-aarch64_be
- It also adjusts CI to use those shells.
- This commit is port from mlkem-native: https://github.com/pq-code-package/mlkem-native/pull/1104

Nix: Introduce separate shells for cross compilation

---

proofs/cbmc/polyvec_matrix_pointwise_montgomery/Makefile
proofs/cbmc/polyvecl_pointwise_acc_montgomery/Makefile

This improves CBMC proof run-time for ML-DSA-44 from 25 minutes to 5 minutes, for ML-DSA-65 from 8 minutes to 6 minutes, and for ML-DSA-87 from 8 minutes to 7 minutes.

CBMC: Increase CBMC_OBJECT_BITS to improve proof runtime

---

mldsa/common.h
mldsa/config.h
mldsa/poly.c
mldsa/sign.c
mldsa/symmetric.h
test/break_pct_config.h
test/custom_memcpy_config.h
test/custom_memset_config.h
test/custom_randombytes_config.h
test/custom_stdlib_config.h
test/custom_zeroize_config.h
test/no_asm_config.h

By default mldsa-native uses the FIPS202 shipped in mldsa/fips202/. However, for some integrations consumers may want to use their own FIPS202 implementations.
This is commonly done using a glue layer such as
https://github.com/pq-code-package/mlkem-native/blob/main/integration/liboqs/fips202_glue.h However, this can lead to clashes in header file names for fips202.h and fips202x4.h
This commit adds the configuration options allowing to customize the included headers for FIPS202.
Resolves https://github.com/pq-code-package/mldsa-native/issues/447
Required for liboqs integration.

Configuration: Add MLD_CONFIG_FIPS202{,X4}_CUSTOM_HEADER

---

Makefile

Previously, the Makefile used .WAIT to order the execution of the benchmarks, breaking compatibility with versions of make prior to 4.4.
This commit fixes this by serializing the benchmark execution explicitly, without relying on .WAIT.
Fixes #427

Makefile: Remove use of .WAIT primitive to support make <4.4

---

proofs/cbmc/Makefile.common

When investigating and/or debugging CBMC proof failures, it can be very useful to generate the SMT file(s), but without actually running the provers. It's also useful to generate the SMT files for one or all of Z3, Bitwuzla, or CVC5 for comparison.
Update Makefile.common for CBMC so that for a function x, new Makefile targets are:
smt: generates gotos/x.smt2 for prover (z3, bitwuzla, or cvc5) chosen by the user in the specific Makefile for that function.
smtz: generates gotos/x.smtz, but always for Z3, ignoring the choice in the Makefile
smtb: generates gotos/x.smtb, but always for Bitwuzla, ignoring the choice in the Makefile
smtc: generates gotos/x.smtc, but always for cvc5, ignoring the choice in the Makefile
smtall: generates all three targets smtz, smtb, smtc as above.

Add Makefile targets to generate SMT files from CBMC

---

proofs/cbmc/polyvecl_pointwise_acc_montgomery/Makefile

Remove --no-array-field-sensitivity to stabilize proof times on all platforms.

Stabilize proof time for polyvecl_pointwise_acc_montgomery()

---

mldsa/cbmc.h

Use COUNTER instead of LINE when creating names of quantified variables. This improves proof stability, since minor changes (such as adding a single blank line) do not affect naming of such variables.
Proof times for all proofs for MLDSA_MODE=2,3,5 respectively:
macOS (8 cores): 8m20s, 10m6s, 9m23s
Grv3/Ubuntu (64 cores): 3m4s, 6m14s, 5m29s

Use COUNTER instead of LINE for quantified variables

---

.github/actions/config-variations/action.yml
.github/workflows/ci.yml
.github/workflows/ci_ec2_reusable.yml

- Resolves: #472 
- This commit introduce separate action in ci, called "config-varation" to align with mlkem-native.

CI: Port config-variation action from mlkem-native

---

integration/liboqs/ML-DSA-44_META.yml
integration/liboqs/ML-DSA-65_META.yml
integration/liboqs/ML-DSA-87_META.yml
scripts/autogen

- Resolves: #517 
- This PR port the OQS source list automatically updating feature from `mlkem-native` to `mldsa-native`,
- The reference code in `mlkem-native`: https://github.com/pq-code-package/mlkem-native/blob/9ae2223e835c1abcc8d6857dd3b7f8ce00a05216/scripts/autogen#L2625
- After porting, run the `autogen` again, add the additional source for each implementations(align with `mlkem-native`) in `ML-DSA-*_META.yml`.

Autogen liboqs file list

---

.github/actions/bench/action.yml
.github/actions/config-variations/action.yml
.github/actions/functest/action.yml
.github/actions/multi-functest/action.yml
.github/workflows/all.yml
.github/workflows/baremetal.yml
.github/workflows/bench.yml
.github/workflows/bench_ec2_any.yml
.github/workflows/bench_ec2_reusable.yml
.github/workflows/ci.yml
Makefile
flake.nix
nix/m55-an547-arm-none-eabi/default.nix
nix/util.nix
scripts/tests
test/baremetal/platform/m55-an547/exec_wrapper.py
test/baremetal/platform/m55-an547/platform.mk
test/mk/components.mk
test/mk/rules.mk

This PR adds initial support for baremetal targets.
General build system changes:
- Add separate LDFLAGS (previously only CFLAGS for both compilation and linking)
- Add EXTRA_MAKEFILE to include custom makefiles with platform-specific configuration
- Add EXTRA_SOURCES to compile and link additional platform files
- Fix ACVP tests to respect EXEC_WRAPPER
Baremetal support for MPS3 AN547 (Arm Cortex-M55):
- Add nix shell (arm-embedded) with arm-none-eabi-gcc, qemu, and platform support files from pqmx
- Add test/baremetal/platform/m55-an547/platform.mk with compiler flags, and build configuration
- Add exec_wrapper.py to pass test arguments via QEMU
- Add CI workflow for functional, KAT, and ACVP tests on AN547

Add initial support for Armv8.1-M targets
