pq-code-package/mldsa-native

proofs/cbmc/poly_add/cbmc-proof.txt

CBMC: Remove cbmc-proof.txt

---

.envrc
.github/actions/setup-nix/action.yml
.github/workflows/nix.yml
.gitignore
flake.lock
flake.nix
nix/cbmc/default.nix
nix/util.nix
scripts/copy_nix_from_upstream
test/mk/rules.mk

ref https://github.com/pq-code-package/mlkem-native/pull/765

Upgrading nix to 24.11 channel

---

mldsa/poly.c
mldsa/poly.h
proofs/cbmc/polyeta_pack/Makefile
proofs/cbmc/polyeta_pack/polyeta_pack_harness.c

Resolves https://github.com/pq-code-package/mldsa-native/issues/27

CBMC: Contract and proof for polyeta_pack

---

.github/workflows/ci.yml
Makefile
scripts/tests
test/bench_components_mldsa.c
test/bench_mldsa.c
test/hal/hal.c
test/hal/hal.h
test/mk/components.mk
test/mk/config.mk

Add benchmarks

---

mldsa/reduce.h
proofs/cbmc/reduce32/Makefile
proofs/cbmc/reduce32/reduce32_harness.c

Resolves https://github.com/pq-code-package/mldsa-native/issues/15

CBMC: Add spec and proof for reduce32

---

mldsa/packing.c
mldsa/packing.h
mldsa/poly.h
mldsa/polyvec.c
mldsa/polyvec.h
proofs/cbmc/pack_pk/Makefile
proofs/cbmc/pack_pk/pack_pk_harness.c
proofs/cbmc/pack_sk/Makefile
proofs/cbmc/pack_sk/pack_sk_harness.c
proofs/cbmc/polyveck_pack_eta/Makefile
proofs/cbmc/polyveck_pack_eta/polyveck_pack_eta_harness.c
proofs/cbmc/polyveck_pack_t0/Makefile
proofs/cbmc/polyveck_pack_t0/polyveck_pack_t0_harness.c
proofs/cbmc/polyveck_unpack_eta/Makefile
proofs/cbmc/polyveck_unpack_eta/polyveck_unpack_eta_harness.c
proofs/cbmc/polyveck_unpack_t0/Makefile
proofs/cbmc/polyveck_unpack_t0/polyveck_unpack_t0_harness.c
proofs/cbmc/polyvecl_pack_eta/Makefile
proofs/cbmc/polyvecl_pack_eta/polyvecl_pack_eta_harness.c
proofs/cbmc/polyvecl_unpack_eta/Makefile
proofs/cbmc/polyvecl_unpack_eta/polyvecl_unpack_eta_harness.c
proofs/cbmc/unpack_pk/Makefile
proofs/cbmc/unpack_pk/unpack_pk_harness.c
proofs/cbmc/unpack_sk/Makefile
proofs/cbmc/unpack_sk/unpack_sk_harness.c

Resolves #70
Resolves #71
Resolves #73
Resolves #74
Depends on #68

CBMC: Add contract and proof for `pack_pk`, `pack_sk`, `unpack_pk`, `unpack_sk`

---

.github/actions/cbmc/action.yml
.github/actions/functest/action.yml
.github/actions/lint/action.yml
.github/actions/multi-functest/action.yml
.github/actions/setup-apt/action.yml
.github/workflows/ci.yml
mldsa/config.h
mldsa/fips202/fips202.c
mldsa/ntt.c
mldsa/reduce.h
test/acvp_mldsa.c
test/bench_mldsa.c
test/gen_NISTKAT.c
test/test_mldsa.c

Depends on #49 (for the scripts). 
Resolves  #55.
This PR achieves C90 compliance (except for `-Wno-long-long` similar to mlkem-native and OpenSSL). 
It also adds C90 compliance testing to CI in addition to extensive compiler tests.

Achieve C90 compliance

---

.clang-format
mldsa/fips202/fips202.c
mldsa/packing.c
mldsa/poly.c
mldsa/polyvec.c
mldsa/rounding.c
mldsa/sign.c
test/acvp_mldsa.c
test/bench_mldsa.c

1. Adds "InsertBraces: true" to .clang-format
2. format
3. lint
4. tests all
All tests OK

Add InsertBraces option for clang-format

---

mldsa/poly.c
mldsa/rounding.c
mldsa/rounding.h
proofs/cbmc/power2round/Makefile
proofs/cbmc/power2round/power2round_harness.c

Resolves https://github.com/pq-code-package/mldsa-native/issues/18

CBMC: Add contract and proof for power2round 

---

mldsa/poly.c
mldsa/poly.h
mldsa/rounding.c
mldsa/rounding.h
proofs/cbmc/decompose/Makefile
proofs/cbmc/decompose/decompose_harness.c
proofs/cbmc/poly_decompose/Makefile
proofs/cbmc/poly_decompose/poly_decompose_harness.c

CBMC: Add contract and proof for `decompose` and `poly_decompose`

---

mldsa/poly.c

The reference implementation comes with some built-in profiling that is inlined into most functions in poly.c.
This is unused in mldsa-native and incompatible with the way our component benchmarks work. For some functions the profiling has already been removed when CBMC proofs were added.
This commit removes all profiling.

Remove unused profiling from poly.c

---

.github/workflows/bench.yml

Depends on #50. Let's merge that first and check if everything works as expected in the main branch.

Add benchmarking (Raspberry Pi 5, Cortex-A55, Banana PI F3)

---

mldsa/poly.h
mldsa/polyvec.h
proofs/cbmc/polyveck_pointwise_poly_montgomery/Makefile
proofs/cbmc/polyveck_pointwise_poly_montgomery/polyveck_pointwise_poly_montgomery_harness.c
proofs/cbmc/polyveck_shiftl/Makefile
proofs/cbmc/polyveck_shiftl/polyveck_shiftl_harness.c
proofs/cbmc/polyvecl_pointwise_poly_montgomery/Makefile
proofs/cbmc/polyvecl_pointwise_poly_montgomery/polyvecl_pointwise_poly_montgomery_harness.c

- Resolves https://github.com/pq-code-package/mldsa-native/issues/128
- Resolves https://github.com/pq-code-package/mldsa-native/issues/120
- Resolves https://github.com/pq-code-package/mldsa-native/issues/131

CBMC: Add contract and proof for further polyvec functions

---

mldsa/ntt.c
mldsa/ntt.h
proofs/cbmc/invntt_layer/Makefile
proofs/cbmc/invntt_layer/invntt_layer_harness.c
proofs/cbmc/invntt_tomont/Makefile
proofs/cbmc/invntt_tomont/invntt_tomont_harness.c

- Resolves https://github.com/pq-code-package/mldsa-native/issues/103
Porting @jakemas's #180 to the main repo to run CBMC CI.

CMBC: Refactor, add contract and proof for invntt_tomont

---

mldsa/fips202/fips202.c
mldsa/fips202/fips202.h
proofs/cbmc/Makefile_params.common
proofs/cbmc/keccakf1600_absorb/Makefile
proofs/cbmc/keccakf1600_absorb/keccakf1600_absorb_harness.c
proofs/cbmc/keccakf1600_absorb_once/Makefile
proofs/cbmc/keccakf1600_absorb_once/keccakf1600_absorb_once_harness.c
proofs/cbmc/keccakf1600_permute/Makefile
proofs/cbmc/keccakf1600_permute/keccakf1600_permute_harness.c
proofs/cbmc/sha3_256/Makefile
proofs/cbmc/sha3_256/sha3_256_harness.c
proofs/cbmc/sha3_512/Makefile
proofs/cbmc/sha3_512/sha3_512_harness.c
proofs/cbmc/shake128_absorb_once/Makefile
proofs/cbmc/shake128_absorb_once/shake128_absorb_once_harness.c
proofs/cbmc/shake256_absorb_once/Makefile
proofs/cbmc/shake256_absorb_once/shake256_absorb_once_harness.c

Continuation of https://github.com/pq-code-package/mldsa-native/pull/167. 
These proofs work fine on my machine, but fail in CI. Testing here if they work if we run them on bigger EC2 boxes.

Add spec and proofs for Keccak dependent functions 

---

mldsa/poly.h
proofs/cbmc/poly_invntt_tomont/Makefile
proofs/cbmc/poly_invntt_tomont/poly_invntt_tomont_harness.c

- Resolves https://github.com/pq-code-package/mldsa-native/issues/106

CBMC: Add contract and proof for poly_invntt_tomont

---

mldsa/polyvec.c
mldsa/polyvec.h
proofs/cbmc/polyveck_invntt_tomont/Makefile
proofs/cbmc/polyveck_invntt_tomont/polyveck_invntt_tomont_harness.c

Resolves https://github.com/pq-code-package/mldsa-native/issues/130

CBMC: Add proof and contract for polyveck_invntt_tomont

---

mldsa/fips202/fips202.h
proofs/cbmc/shake128_absorb/Makefile
proofs/cbmc/shake128_absorb/shake128_absorb_harness.c
proofs/cbmc/shake128_finalize/Makefile
proofs/cbmc/shake128_finalize/shake128_finalize_harness.c
proofs/cbmc/shake128_init/Makefile
proofs/cbmc/shake128_init/shake128_init_harness.c

- Resolves https://github.com/pq-code-package/mldsa-native/issues/148
- Resolves https://github.com/pq-code-package/mldsa-native/issues/149
- Resolves https://github.com/pq-code-package/mldsa-native/issues/150

CBMC: Add proof and contract for shake128_init _absorb _finalize

---

RELICENSE.md

This adds my approval to RELICENSING.md as required by #215.

Add RELICENSING.md approval for Pravek Sharma

---

mldsa/poly.c
mldsa/poly.h
proofs/cbmc/poly_uniform/Makefile
proofs/cbmc/poly_uniform/poly_uniform_harness.c

* Resolves https://github.com/pq-code-package/mldsa-native/issues/110

CBMC: Add proof and contract for poly_uniform

---

mldsa/poly.c
mldsa/poly.h
proofs/cbmc/poly_uniform_eta/Makefile
proofs/cbmc/poly_uniform_eta/poly_uniform_eta_harness.c

- Resolves https://github.com/pq-code-package/mldsa-native/issues/111

CBMC: Add proof and contract for poly_uniform_eta

---

mldsa/polyvec.c
mldsa/polyvec.h
proofs/cbmc/polyveck_uniform_eta/Makefile
proofs/cbmc/polyveck_uniform_eta/polyveck_uniform_eta_harness.c

- Resolves https://github.com/pq-code-package/mldsa-native/issues/123
- Depends on #224

CBMC: Add proof and contract for polyveck_uniform_eta 

---

mldsa/polyvec.c
mldsa/polyvec.h
proofs/cbmc/polyvecl_uniform_eta/Makefile
proofs/cbmc/polyvecl_uniform_eta/polyvecl_uniform_eta_harness.c

- Resolves https://github.com/pq-code-package/mldsa-native/issues/114
Merge after https://github.com/pq-code-package/mldsa-native/pull/224

CBMC: Add proof and contract for polyvecl_uniform_eta

---

mldsa/poly.h
proofs/cbmc/poly_uniform_gamma1/Makefile
proofs/cbmc/poly_uniform_gamma1/poly_uniform_gamma1_harness.c

- Resolves https://github.com/pq-code-package/mldsa-native/issues/112

CBMC: Add proof and contract for poly_uniform_gamma1 

---

mldsa/fips202/fips202.c

1. Avoid pointer arithmetic on "out" parameter, and use an integer-value out_offset instead, and array-index assignment.
2. Leave "outlen" parameter constant so it can be used unmodified in CBMC assigns() clauses.
3. Modify loop invariants appropriately.
Proof time on Apple M1 now 6 seconds instead of c. 130 seconds.

Re-factor keccak_squeeze() to improve proof time.

---

nix/cbmc/0001-Do-not-download-sources-in-cmake.patch
proofs/cbmc/.gitignore

Porting https://github.com/pq-code-package/mlkem-native/pull/1017

Fix relicensing gap

---

mldsa/fips202/fips202x4.h
mldsa/poly.h
mldsa/polyvec.h
proofs/cbmc/poly_uniform_gamma1_4x/Makefile
proofs/cbmc/poly_uniform_gamma1_4x/poly_uniform_gamma1_4x_harness.c
proofs/cbmc/polyvecl_uniform_gamma1/Makefile
proofs/cbmc/polyvecl_uniform_gamma1/polyvecl_uniform_gamma1_harness.c
proofs/cbmc/shake256x4_absorb_once/Makefile
proofs/cbmc/shake256x4_absorb_once/shake256x4_absorb_once_harness.c
proofs/cbmc/shake256x4_squeezeblocks/Makefile
proofs/cbmc/shake256x4_squeezeblocks/shake256x4_squeezeblocks_harness.c

- Resolves #246 
- Resolves #247 
- Resolves #252
- Resolves #115

Add CBMC proof and spec for `polyvecl_uniform_gamma1`, `poly_uniform_gamma1_4x`, `mld_shake256x4_absorb_once`, `mld_shake256x4_squeezeblocks`

---

mldsa/polyvec.c
mldsa/polyvec.h
proofs/cbmc/polyvecl_chknorm/Makefile
proofs/cbmc/polyvecl_chknorm/polyvecl_chknorm_harness.c

- Resolves https://github.com/pq-code-package/mldsa-native/issues/122

CBMC: Added proof and contract for polyvecl_chknorm

---

mldsa/polyvec.c
mldsa/polyvec.h
proofs/cbmc/polyvec_matrix_expand/Makefile
proofs/cbmc/polyvec_matrix_expand/polyvec_matrix_expand_harness.c

Resolves https://github.com/pq-code-package/mldsa-native/issues/137

CBMC: Add proof and spec for polyvec_matrix_expand

---

README.md
mldsa/polyvec.c
mldsa/polyvec.h
proofs/cbmc/polyvec_matrix_pointwise_montgomery/Makefile
proofs/cbmc/polyvec_matrix_pointwise_montgomery/polyvec_matrix_pointwise_montgomery_harness.c
proofs/cbmc/polyvecl_pointwise_acc_montgomery/Makefile
proofs/cbmc/polyvecl_pointwise_acc_montgomery/polyvecl_pointwise_acc_montgomery_harness.c

- Resolves https://github.com/pq-code-package/mldsa-native/issues/121
- Resolves https://github.com/pq-code-package/mldsa-native/issues/138

CBMC: Add proof and spec for `polyvecl_pointwise_acc_montgomery` and `polyvec_matrix_pointwise_montgomery`

---

mldsa/sign.c

Fixes #265 
Refactor crypto_sign_signature_internal() to remove goto statements and introduce a loop statement, so that an invariant can be inserted for later CBMC proof.
Tests and lint OK. Proof will follow after completion of proofs in polyvec.[hc]

Refactor crypto_sign_signature_internal() to remove goto statements

---

mldsa/poly.c
mldsa/poly.h
mldsa/polyvec.c
mldsa/polyvec.h
mldsa/sign.c
proofs/cbmc/poly_add/poly_add_harness.c
proofs/cbmc/polyveck_add/polyveck_add_harness.c
proofs/cbmc/polyvecl_add/polyvecl_add_harness.c

Change poly_add and vector-variants and add proof and spec for poly_add, polyveck_add, polyvecl_add
Resolves #172

CBMC and refactor: Change poly_add and vector-variants and add proof 

---

mldsa/config.h
mldsa/sign.c
mldsa/sign.h
proofs/cbmc/check_pct/Makefile
proofs/cbmc/check_pct/check_pct_harness.c

- Resolves https://github.com/pq-code-package/mldsa-native/issues/271

Add Pairwise Consistency Test (PCT) for FIPS-204 IG compliance

---

Makefile

* Resolves #386
Port of https://github.com/pq-code-package/mlkem-native/pull/1131.

Makefile: Detect suitable sha256sum tool and set -o pipefail

---

.github/actions/ct-test/action.yml
.github/workflows/all.yml
.github/workflows/ct-tests.yml
mldsa/config.h
mldsa/native/aarch64/meta.h
mldsa/native/x86_64/meta.h
mldsa/poly.c
mldsa/sign.c
test/test_mldsa.c

- Based on #371 
- Resolves #379

Add valgrind-based constant-time tests

---

.github/workflows/ci.yml
.github/workflows/ct-tests.yml
flake.lock
flake.nix

Porting from https://github.com/pq-code-package/mlkem-native/pull/1141

nix/CI: Add gcc15 tests

---

.github/workflows/ci.yml
.github/workflows/ct-tests.yml
.github/workflows/nix.yml
CONTRIBUTING.md
flake.lock
flake.nix

See https://github.com/pq-code-package/mlkem-native/pull/1140

Add clang 21 to compiler and constant-time tests

---

.github/workflows/ci.yml
flake.nix

- This PR is ported from https://github.com/pq-code-package/mlkem-native/pull/1183
- This PR add compiler test for zig 0.15

Add compiler test for zig 0.15

---

flake.nix
nix/cbmc/default.nix

- This PR is ported from https://github.com/pq-code-package/mlkem-native/pull/1151
- This PR update the bitwuzla from 0.7.0 to 0.8.2 in nix

bitwuzla: update the bitwuzla version from 0.7.0 to 0.8.2 in nix

---

mldsa/native/aarch64/meta.h
mldsa/native/aarch64/src/arith_native_aarch64.h
mldsa/native/aarch64/src/poly_use_hint_32_asm.S
mldsa/native/aarch64/src/poly_use_hint_88_asm.S
mldsa/native/api.h
mldsa/native/x86_64/meta.h
mldsa/native/x86_64/src/arith_native_x86_64.h
mldsa/native/x86_64/src/poly_use_hint_32_avx2.c
mldsa/native/x86_64/src/poly_use_hint_88_avx2.c
mldsa/poly.c

- Resolves #398
- Resolves #400
- Resolves #306

Add native implementation of poly_use_hint

---

.github/actions/setup-oqs/action.yml
.github/workflows/all.yml
.github/workflows/integration-liboqs.yml
integration/liboqs/ML-DSA-44_META.yml
integration/liboqs/ML-DSA-65_META.yml
integration/liboqs/ML-DSA-87_META.yml
integration/liboqs/config_aarch64.h
integration/liboqs/config_c.h
integration/liboqs/config_x86_64.h
integration/liboqs/fips202_glue.h
integration/liboqs/fips202x4_glue.h
mldsa/native/aarch64/src/arith_native_aarch64.h

- Resolves #162 
- Depends on #476 
- Depends on #478

Prototype liboqs integration
